### ISSUE TITLE
Script not opening with Url

### ISSUE THREAD

**Issue by GrameJunior** [Andreas-Bresch/vmailManage#1]
When i tried to open the interface with the link, i got to a file explorer. I needed to rename the app.php to index.ph to start automatically.

**Comment by Andreas-Bresch** [comment]
Did you checked out the whole project?
There has to be a ".htacces" file in the folder "web" and there is defined, that app.php is used as index-page, something like: 

> DirectoryIndex app.php

Because of security, a file explorer you should never see!
