### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '/var/www/html/vmailManage/web/../vendor/autoload.php' 

### ISSUE THREAD

**Issue by deiszner** [Andreas-Bresch/vmailManage#10]
Moin,

wenn ich nach der Anleitung im Wiki vorgehe (debian 9.1), dann kommt zum schluss beim Aufruf des Webinterface:

[Tue Dec 12 14:34:40.396321 2017] [:error] [pid 3331] [client XXX.XXX.XXX.XXX:59703] PHP Fatal error:  require(): Failed opening required '/var/www/html/vmailManage/web/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/vmailManage/web/app.php on line 5

Hier fehlen scheinbar für die Ausführung noch weitere Bibliotheken?

gruß & danke
debianfan

**Comment by Andreas-Bresch** [comment]
Hey,

die autoload lädt Module nach und löst Namespaces auf, ich gucke mir das die Tage mal an, aber eigentlich sollten keine Bibliotheken fehlen.
Gruß
Andreas

Von meinem iPhone gesendet

**Comment by deiszner** [comment]
Wenn Du noch mehr Hintergrundinfos brauchst, lass ich mich bitte wissen.

**Comment by Andreas-Bresch** [comment]
Hey,
endlich habe ich etwas Zeit.
Konntest Du das Problem zwischenzeitlich lösen?
Grüße
Andreas

**Comment by deiszner** [comment]
nein :-/

jetzt nörgelt er noch am .htaccess herum

**Comment by Andreas-Bresch** [comment]
Sorry, ich bin gerade ohne Computer im Urlaub.
Hattest du das mit dem Autoload gelöst? Woran lag es?
Was bemängelt er denn bei der .htaccess?


Von meinem iPhone gesendet

**Comment by Andreas-Bresch** [comment]
Konntest du das Problem lösen?
Es trat bei anderen Benutzern leider auch auf.
Ich konnte die Problematik an einem frisch aufgesetzten Testsysten leider nicht reproduzieren.
Vielleicht liegt es an debian? Ich habe es mit Ubuntu Server 14.04 getestet.

Grüße

**Comment by selliw** [comment]
hallo
ich habe das gleiche problem mit Debian GNU/Linux 9.3 (stretch).
wenn ich mal nach der datei autoload.php suche finde ich folgendes aber KEIN vendor verzeichnis !!
/usr/share/phpmyadmin/libraries/sql-parser/autoload.php
/usr/share/phpmyadmin/libraries/plugins/auth/recaptcha/autoload.php
/usr/share/php/JsonSchema/autoload.php
/usr/share/php/Composer/Semver/autoload.php
/usr/share/php/Composer/autoload.php
/usr/share/php/Composer/Spdx/autoload.php
/usr/share/php/Composer/CaBundle/autoload.php
/usr/share/php/Symfony/Component/Process/autoload.php
/usr/share/php/Symfony/Component/Console/autoload.php
/usr/share/php/Symfony/Component/Filesystem/autoload.php
/usr/share/php/Symfony/Component/Finder/autoload.php
/usr/share/php/Symfony/Polyfill/Mbstring/autoload.php
/usr/share/php/Psr/Log/autoload.php
/usr/share/php/Seld/JsonLint/autoload.php
/usr/share/php/Seld/CliPrompt/autoload.php
/usr/share/php/phpseclib/autoload.php

nach einer suche ueber google muss ein php-composer installiert werden.
jedoch fragt sich wie, damit er erkannt wird.

vielleicht fehlt hier genau dieses !!

mfg ralf

**Comment by Andreas-Bresch** [comment]
Hey,
hast Du den folgenden Befehl ausgeführt:

cd vmailManage/
composer install --no-interaction

Der müsste alle Abhängigkeiten nach „vendor“ laden und die „autoload“ anlegen.

Hilft das weiter?
Andreas

**Comment by deiszner** [comment]
Funktioniert 😊

 

Das war die Lösung

 

Von: Andreas Bresch [mailto:notifications@github.com] 
Gesendet: Mittwoch, 7. Februar 2018 13:28
An: Andreas-Bresch/vmailManage <vmailManage@noreply.github.com>
Cc: debianfan <sebastian@deiszner.de>; Author <author@noreply.github.com>
Betreff: Re: [Andreas-Bresch/vmailManage] PHP Fatal error: require(): Failed opening required '/var/www/html/vmailManage/web/../vendor/autoload.php' (#10)

 

Hey,
hast Du den folgenden Befehl ausgeführt:

cd vmailManage/
composer install --no-interaction

Der müsste alle Abhängigkeiten nach „vendor“ laden und die „autoload“ anlegen.

Hilft das weiter?
Andreas

**Comment by selliw** [comment]
hallo
wenn ich den oberen befehl ausführe erhalte ich folgendes:

root@www5:/var/www/html/vmailManage# composer install --no-interaction
PHP Warning:  require(): open_basedir restriction in effect. File(/usr/share/php/Composer/autoload.php) is not within the allowed path(s): (/var/www/:/tmp/:/var/nextcloud_data) in /usr/bin/composer on line 10
PHP Warning:  require(/usr/share/php/Composer/autoload.php): failed to open stream: Operation not permitted in /usr/bin/composer on line 10
PHP Fatal error:  require(): Failed opening required 'Composer/autoload.php' (include_path='.:/usr/share/php') in /usr/bin/composer on line 10
root@www5:/var/www/html/vmailManage#

ich habe php7 installiert.
jetzt weiss ich nicht weiter und benötige hilfe.
würde mich auf ein re freuen.

mjfg ralf

**Comment by Andreas-Bresch** [comment]
Hast du in der php.ini den open_basedir - Eintrag geändert?
Oder setzt du Plesk ein?
Dein Composer kann sich nicht korrekt initialisieren, da er auf das genannte Verzeichnis nicht zugreifen darf.



Von meinem iPhone gesendet

> Am 07.02.2018 um 23:30 schrieb selliw <notifications@github.com>:
> 
> hallo
> wenn ich den oberen befehl ausführe erhalte ich folgendes:
> 
> root@www5:/var/www/html/vmailManage# composer install --no-interaction
> PHP Warning: require(): open_basedir restriction in effect. File(/usr/share/php/Composer/autoload.php) is not within the allowed path(s): (/var/www/:/tmp/:/var/nextcloud_data) in /usr/bin/composer on line 
>

**Comment by selliw** [comment]
hallo
ich setze kein Plesk ein. sondern nur eine debian 9.3 stretch installation auf den neusten stand.
ich habe nach php.ini gesucht weil ich ja php7 einsetze.
danach habe ich in die  /etc/php/7.0/fpm/php.ini geschaut - alles ok
aber in der  /etc/php/7.0/cli/php.ini habe ich den  open_basedir von 
open_basedir = /var/www/:/tmp/:/var/nextcloud_data
auf
open_basedir =
gesetzt. nach einem
composer install --no-interaction
bekam ich  7. Probleme/Fehler also ein update
composer update
das lief auch soweit durch bis ich den fehler:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the symfony-scripts event terminated with an exception
  [Symfony\Component\Yaml\Exception\ParseException]
  Unable to parse at line 23 (near "    secret: ThisTokenIsNotSoSecretChangeIt").
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

bekam.
irgendwie muss hier ein token erzeugt werden. leider weiss ich nicht wie :-((
wuerde mich auf ein re freuen.

mfg ralf

**Comment by selliw** [comment]
hallo
habe mal ein wenig weiter gemacht. obs richtig ist weiss ich nicht :-(
datei
/srv/raid/www/html/vmailManage/app/config/parameters.yml 
angesehen - hier war der eintrag secret: 2 mal drin
secret: ThisTokenIsNotSoSecretChangeIt
secret: ****
also beide auskommentiert und nochmal
composer install --no-interaction
das lief dann ohne probleme durch. **freu**
nun steht in der
/srv/raid/www/html/vmailManage/app/config/parameters.yml
nur noch
secret: ThisTokenIsNotSoSecretChangeIt
drin
soweit so gut
wenn ich nun den webbrowser starte erhalte ich zeitueberschreitung
wenn ich die .htaccess umbenenne bekomme ich eine abfrage bei https
wegen ssl - das ganze akzeptiere ich und erhalte dann eine leere weisse seite :-((
im log von apache steht dann drin:
[Thu Feb 08 23:23:45.252400 2018] [:error] [pid 4399] [client 192.168.1.103:54560] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() 
must be an instance of string, string given, called in /srv/raid/www/html/vmailManage/var/cache/prod/classes.php on line 6406 and defined' in
in /srv/raid/www/html/vmailManage/vendor/twig/twig/lib/Twig/Filter.php:35\nStack trace:\n#0 /srv/raid/www/html/vmailManage/var/cache/prod/classes.php(6406): 
 Twig_Filter->__construct('date', 'twig_date_forma...', Array)\n#1 /srv/raid/www/html/vmailManage/vendor/twig/twig/lib/Twig/ExtensionSet.php(439): Twig_Extension_Core->getFilters()\n#2 
/srv/raid/www/html/vmailManage/vendor/twig/twig/lib/Twig/ExtensionSet.php(429): Twig_ExtensionSet->initExtension(Object(Twig_Extension_Core))\n#3 
.....
bis n#5

damit kann ich nun wieder nix anfangen
ich mach mal weiter - langsam wird das ein Tagebuch :-)
mfg ralf

**Comment by selliw** [comment]
nachtrag
composer info
...
twig/twig                            v2.4.4  Twig, the flexible, fast, and secure template language for PHP
...

mm wenn ich das richtig verstanden habe muss zwischen php5 und php7
an der twig was gedreht werden :-(

mfg ralf

**Comment by selliw** [comment]
hallo
so weiter gehts - wen alles nicht mehr geht fängt manvon vorne an.
also neuen rechner neues glück
jetzt mit einen raspberry pi
Description:    Raspbian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch

habe alles nochmal durchgeführt und siehe da es funktioniert. ***freu***
suche des problems
composer info auf beiden systemen eingegeben und siehe da
system welches nicht geht:
symfony/symfony  v3.3.16
twig/twig v2.4.4
system welches funktioniert:
symfony/symfony v3.3.4
twig/twig v1.34.4

so - ergebnis - ich werde auf dem nichtfunktionierenden composer rechner das komplette
composer paket runterwerfen inkl. vmailManage und neu aufsetzen. mal sehen obs geht.
werde hier dann eine info schreiben.

mfg ralf

**Comment by Andreas-Bresch** [comment]
Super, danke für die Info!
Viele Grüße & Erfolg
Andreas

Von meinem iPhone gesendet

**Comment by selliw** [comment]
hallo
zwischenbericht
also alles runter und neu aufgesetzt. soweit so gut
jetzt sehe ich auch:
symfony/symfony v3.3.4
twig/twig v1.34.4
nachdem ich nun im webbrowser die seite aufgerufen habe kommt auch
die startseite von vmailManage und das login
nach dem login kommt:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
:-((
mal in die log geschaut vom apache2 /var/log/apache2/error.log
[Sun Feb 11 00:28:04.675039 2018] [:error] [pid 27467] [client 192.168.1.103:50709] PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /srv/raid/www/html/vmailManage/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:
......Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 
... korrekte logindaten stehen dann hier
PDOMySql/Driver.php(45) ......
Doctrine\\DBAL\\Connection->getDatabasePlatformVersion in /srv/raid/www/html/vmailManage/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115

die login daten stimmen aber warum findet er den mysql-driver nicht :-(((
falsche VERSION ???
auf dem raspberry :  10.1.23-MariaDB-9+deb9u1
auf dem debian rechner: 10.1.26-MariaDB-0+deb9u1
sollte hier der fehler liegen.
irgendwo habe ich gefunden wo man da was drehen kann, aber ich weiss nicht mehr wo.
brauche also mal hilfe

auf ein re
mfg ralf

**Comment by Andreas-Bresch** [comment]
Hattest du die php MySQL Bibliotheken installiert (mariaDB ist ja dazu kompatibel)?



Von meinem iPhone gesendet

**Comment by selliw** [comment]
hallo
die installation von vmailManage erfolgte nach der anleitung.
mariaDB habe ich auch installiert und läuft.
ich denke auch das hier was fehlt - aber ich weiss nicht was.
fällt dir dazu was ein ??
apt-get install mariadb-server
das habe ich gemacht. was muss ich noch installieren für vmailManage/composer

mfg ralf

**Comment by Andreas-Bresch** [comment]
Also alle Abhängigkeiten sind in der composer.json 
aufgeführt. 
Aber die DB sollte ja über die php-MySQL-Installation abgedeckt sein.
Und diese dann über
app/config/config.yml
konfiguriert werden: 
pdo_mysql
muss da stehen.
Kommt das hin?

Von meinem iPhone gesendet

**Comment by vzsze** [comment]
Ich hatte ein ähnliches Problem. Die Lösung war, dem Datenbankuser auch insert, update and delete Rechte zu geben.

**Comment by selliw** [comment]
hallo nochmal
***freu***
alles geht super. ich habe den fehler gefunden. wenn man weiss wo man suchen muss ;-))
FEHLER:
ich hatte php5 installiert mit meinem apache und auch konfiguriert.
soweit so gut.
da ich aber auf php7 umsteigen wollte habe ich dieses paket mit apt-get purge
geloescht und wie in dieser anleitung php7 installiert.
also php5 weg php7 drauf und apache suchte immer noch nach php5,
weil das modul installiert war im apache.

LOESUNG:
im apache eine phpinfo.php erstellt und nachgesehen was installiert ist. hier fehlten die kompletten:
Additional .ini files parsed  -- files. also nix mit /etc/php/7.0/apache2/conf.d/20-pdo_mysql.ini
klar das er somit nix finden konnte.
also apache soweit konfiguriert das erst mal die ganzen ini files zu finden sind fuer die 7.0 version.
genauer: PHP Version 7.0.27-0+deb9u1
auch die module eingeschaltet !!!!!! und ein restart vom apache !!!!!!! kontrolle ueber die phpinfo.php
was nun alles installiert ist und siehe da...
viele, viele ini scripts und ganz ganz wichtig weiter unten auf der website:
PDO drivers  --- mysql
und
pdo_mysql ---- Client API version | mysqlnd 5.0.12-dev - 20150407
somit findet nun der composer auch den driver von mysql und vmailManage
laeuft super

war eine schwere geburt aber bin nun zufrieden ***freu***

stellt sich nun die frage fuer mich, kann ich das vmailManage auch erweitern/programmierschnittstelle/
anleitung um das ganze zu erweitern.
gibt es da im netzt eine beschreibung ???

wuerde mich auf ein re freuen.

mfg ralf

**Comment by Andreas-Bresch** [comment]
Hey,

ich war im Urlaub :)

Schön dass es nun funktioniert.

Ja klar kannst du es erweitern. 
Hier waren auch schon andere Ideen, was man noch alles machen könnte.
Was schwebt dir denn vor?

Eine Anleitung gibt es nicht, aber wenn du die Symfony etwas anguckst, findest du dich bestimmt schnell zurecht.

Viele Grüße 
Andreas

Von meinem iPhone gesendet
