### ISSUE TITLE
Kann nichts ändern oder Anlegen

### ISSUE THREAD

**Issue by Arnek1** [Andreas-Bresch/vmailManage#13]
Hallo Andreas,

ich habe Dein Interface installiert und kann mich auch mit dem Namen dem ich die Admin-rolle gegeben habe einloggen. Es werden alle domains, accounts aliase usw. angezeigt wenn ich aber etwas änderrn oder anlegen möchte bekomme ich die Fehlermeldung im Browser das die Seite nicht existiert.
Z.b: "The requested URL /account/1 was not found on this server." Wenn ich den ersten account ändern will.
Irgenteinen Tipp wo ich ansetzten kann das zu korrigieren?
Danke!

Arne

**Comment by Andreas-Bresch** [comment]
Hey Arne.
Hmm Account/1 sollte über 
src/AppBundle/Controller/editAccountController.php

aufgelöst werden. Existiert diese Datei mit entsprechenden Rechten?

Andreas


Von meinem iPhone gesendet

**Comment by Arnek1** [comment]
Hallo Andreas,
die Rechte sehen für alle Dateien im Verzeichniss so aus (ls -la):
-rw-r--r-- 1 www-data www-data 2556 Dec 24 15:48 editAccountController.php

Müssen die Dateien für den user www-data auch ausführbar sein?

Gruß
Arne

**Comment by Andreas-Bresch** [comment]
Stimmt da etwas mit dem Routing nicht? Kontrolliere bitte nochmal Deine .htaccess und ob im Apache das Forwarding richtig eingestellt ist (bin mir nicht sicher, ob man es braucht, ich habe die Tage keinen Computer zur Hand).
Vielleicht hilft es ja.
Grüße 
Andreas

Von meinem iPhone gesendet

**Comment by Andreas-Bresch** [comment]
Hallo Arne,
mit dem letzten Merge hier auf Github hatte etwas nicht gestimmt. Ich habe nun auf das alte Layout zurückgerollt. 
Du kannst Dir ja mal den aktuellen Branch herunterladen und antesten.
Viele Grüße von Andreas

**Comment by Arnek1** [comment]
Hallo Andreas,

danke für den Hinweis. Funktioniert jetzt alles.

Vielen Dank!

Grüße

Arne

**Comment by Andreas-Bresch** [comment]
:)
