### ISSUE TITLE
After installation, only the directory index is shown; no login possible

### ISSUE THREAD

**Issue by lhitc** [Andreas-Bresch/vmailManage#3]
When I install according to the install doc, I only see the directory index.
Also it is not clear how to login. When clicking on app.php in the browser, I see the menu, but no data and no possibility to log in.

**Comment by lhitc** [comment]
This is related to #1  - you can't assume that Apache by default accepts .htaccess files (Debian and Ubuntu default installs do not). At least mention it in the documentation.

**Comment by Andreas-Bresch** [comment]
Okay, thanks for this tip. 
I will prove it and expand the documentation.

**Comment by Andreas-Bresch** [comment]
Hey Stefan,
also ich habe nochmal einen Testserver aufgesetzt und meine Anleitung korrigiert.
Da hatte ja ganz schön viel gefehlt :(
Du hast es ja zum Glück dennoch zum Laufen bekommen, aber hier nochmal die wichtigsten Punkte:

SSL (also https) ist auf jeden Fall eine gute Idee, ich habe meinen Server so konfiguriert, dass er immer nach https umleitet. Außerdem muss das rewrite-Modul aktiviert sein, damit die Unterseiten aufgerufen werden können - aber das hattest du ja hinbekommen.

a2enmod ssl
a2ensite default-ssl
a2enmod rewrite

So sollte korrekterweise die Konfiguration vom Apache sein, damit Seiten ohne Index nicht angezeigt werden:

vim /etc/apache2/apache2.conf

<Directory /var/www/html/vmailManage/>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</ Directory>

Wenn Dir noch was einfällt, dann gib Bescheid.

Viele Grüße von
Andreas

**Comment by lhitc** [comment]
Es war halt ein bisschen Zusatz-Arbeit, es hinzubekommen und wenn man gerade von der Thomas-Leister-Doku kommt (Copy, Paste, Enter, Repeat - works) ein ziemlicher Unterschied :)

Am Ende waren es ja nur die fehlenden PHP-Extensions (die Fehlermeldung vom Symfony-Installer ist da nicht sehr hilfreich) und halt .htaccess.
Und klar, HTTPS sollte für ein Admin-Interface selbstverständlich sein.
Auf jeden Fall denke ich, es passt jetzt :+1:
