### ISSUE TITLE
Configuration ist readable from the browser

### ISSUE THREAD

**Issue by lhitc** [Andreas-Bresch/vmailManage#4]
When following the install doc, I can browse to the app/config directory and open the YAML files containing DB and user passwords.
It should either be protected (and/or mentioned how to protect) or better make only web/ accessible from the browser

**Comment by Andreas-Bresch** [comment]
The .htaccess should forbid it.
Maybe you edited the /etc/apache2/apache2.conf?
Change "AllowOverride None" to "AllowOverride All" for the directory of the webinterface. 
Regards
Andreas
