### ISSUE TITLE
New Webinterface With Bootstrap 3 / 4

### ISSUE THREAD

**Issue by axiades** [Andreas-Bresch/vmailManage#5]
Hello,
Is it possible to refresh the webinterface with [bootstrap](https://getbootstrap.com/)?

The current template is not really user-friendly.

Best regards

**Comment by Andreas-Bresch** [comment]
Why is it not user-friendly?
Do you manage your server on a mobile device?
Somewhen I can make it, but at the moment my phpstorm license is out of date and I get a new one only in two month for free, but you can donate ;)
Greeting
Andreas

**Comment by axiades** [comment]
Where can i Edit the Forms for Create new Account, Domain & Alias?

ive edited the Tables to Bootstrap tables.

![alias](https://user-images.githubusercontent.com/19848667/29248383-3121765c-8017-11e7-8424-049a2fbf42a7.png)

Hope you can help me and tell me where I find the forms to create.

If you want this template just write it.

Best Regards

**Comment by Andreas-Bresch** [comment]
Cool.
The forms are created automatically by using FormBuilder.
The configuration you will find under src\AppBundle\Form\

**Comment by msphn** [comment]
Just a little hint @philliplurge http://bootstrap.braincrafted.com/

This automatically improves the form generation of symfony to work with bootstrap.

**Comment by Andreas-Bresch** [comment]
@philliplurge did you managed it?
@cookiekiller thanks for the link, later I will have a look on it.

**Comment by axiades** [comment]
until now Not.. with the link from coockiekiller

**Comment by msphn** [comment]
Oh and btw. I think more recent versions of symfony already ship some bootstrap templates for forms etc.

**Comment by Mesqualito** [comment]
Sry, I cannot enter the interface. 

I read the documentation in https://symfony.com/doc/current/security.html, and checked whether everything seems fine in my config, even no tabs in yaml ;-)
I added and "used" a file called flush_cache.php (see https://ma.ttias.be/how-to-clear-php-opcache ) - no help.

I didn't find a log to this "error" except apaches access.log (logically no error there) and the login-form only shows "Invalid credentials." on every page (domain, account, alias) when I try to log in. An apache2ctl graceful didn't help nor did a change of username and password in the app/config/security.yml; I uncommented the standard admin - kitten for a test, with no further result, too.

Do you have some hint for me where to look at? I don't know symfony at all but it looks nice at first glance (this project :-) .

Btw. I am using https://thomas-leister.de/mailserver-debian-stretch which can also be linked as far as he mentions.


Thanks in advance,

Jochen

**Comment by Andreas-Bresch** [comment]
@Mesqualito 
please, can you copy your request to a new issue?
Did you checked file-permissions?
Andreas

**Comment by axiades** [comment]
@Andreas-Bresch Währe es ggf Möglich dass Webinterface nochmal mit Bootstrap zu rewriten?
bekomme es nicht hin mit dem Link von Coockiekiller

**Comment by Andreas-Bresch** [comment]
Ok, ich gucke es mir an. Kann aber 2-3 Wochen dauern...

**Comment by Andreas-Bresch** [comment]
@philliplurge have a look at this branch, @Radiergummi did a nice layout.
