### ISSUE TITLE
Do not use .htaccess files

### ISSUE THREAD

**Issue by m0llux** [Andreas-Bresch/vmailManage#6]
There are other web servers besides apache. I would like to use nginx with vmailManage, but the use of .htaccess files prevents this. 

Could you explain why the use of .htaccess files is necessary and/or provide a working nginx config?

Thanks :)

**Comment by Andreas-Bresch** [comment]
Because of security the .htaccass is very important.
It forbids to browse the directories and open configuration files.
Besides it sets the directory-index to app.php and manages the rewrite-rules.

But it is possible to run it with nginx. Look here https://www.google.de/search?q=nginx+symfony

**Comment by m0llux** [comment]
Alright thanks!
