### ISSUE TITLE
Login not possible in ADMIN-ROLE

### ISSUE THREAD

**Issue by Mesqualito** [Andreas-Bresch/vmailManage#7]
Sry, I cannot enter the interface.

I read the documentation in https://symfony.com/doc/current/security.html, and checked whether everything seems fine in my config, even no tabs in yaml ;-)
I added and "used" a file called flush_cache.php (see https://ma.ttias.be/how-to-clear-php-opcache ) - no help.

I didn't find a log to this "error" except apaches access.log (logically no error there) and the login-form only shows "Invalid credentials." on every page (domain, account, alias) when I try to log in. An apache2ctl graceful didn't help nor did a change of username and password in the app/config/security.yml; I uncommented the standard admin - kitten for a test, with no further result, too.

Do you have some hint for me where to look at? I don't know symfony at all but it looks nice at first glance (this project :-) .

Btw. I am using https://thomas-leister.de/mailserver-debian-stretch which can also be linked as far as he mentions.

Thanks in advance,

Jochen

**Comment by Andreas-Bresch** [comment]
Did you checked file-permissions?
Did you customized app/config/parameters.yml too?
Andreas

**Comment by Mesqualito** [comment]
Q: Did you checked file-permissions?
Via apache2 proxy I declared in virtual host:

                ...
                DocumentRoot /var/www/secure.[xxx].net

                Alias /vmailmanage /var/www/webmail.[xxx].net/vmailManage/web
                <Directory "/var/www/webmail.[xxx].net/vmailManage">
                Options -Indexes +FollowSymLinks
                AllowOverride All
                Require all granted
                </Directory>
                ...

In vmailManage all is www-data.www-data and 770 (which is very open, right?).

Q: Did you customized app/config/parameters.yml too?

I only changed security.yml and of course parameters.yml.

Sincerely,
Jochen

**Comment by Andreas-Bresch** [comment]
Maybe you make an typing error in security.yml?
You can load it again.
And after this, if it not works, uncomment the last 3 lines under access_control (disable security login).
Greetings

**Comment by Mesqualito** [comment]
hm, after

     git checkout --theirs security.yml
     git pull origin master

I tried to login again. Now, there is a 500 (Internal Server Error) on every (reachable) site (/domain, /account, /alias). I did the flushing and also a testing "apache2ctl graceful". No error-logging (LogLevel info ssl:warn).

In parameters.yml, I did change the secret-"key"; and mailer_user, mailer_password are null. The database-credentials are working (on bash - mysql). Is there a problem with changing the secret-key?

Thanks!

Jochen

**Comment by Andreas-Bresch** [comment]
After checkout, you set the file permissions?
Try to comment the last lines in security.yml and test it again.
ok?

**Comment by Mesqualito** [comment]
After changing users in security.yml again, the error 500 is gone...

File permissions as described above, changed it after pull.
I tried with commenting out the access_control, as  you mentioned (forgot to tell in my last post...) and now once again. Strange behaviour is now (with access_control - lines commented out): the login-page appears. And it is not possible to login, with or without user & password.
Shouldn't the login-page disappear, when access_control is "off"?

Once again, the only logs are in access.log (that's fine), but there is no error in apache's error.log.

**Comment by Andreas-Bresch** [comment]
hmmm,
I tested it now, if the last lines commented ("#") there is no login dialog and it works.
Maybe it is a caching-problem. Did you 
`php bin/console cache:clear --no-warmup --env=prod`
after change security.yml?

**Comment by Mesqualito** [comment]
Sorry for bothering you this long...

To clear the cache: is there any other way except installing php as binary for the bash? I prefer this solution: https://ma.ttias.be/how-to-clear-php-opcache - on both ways, with a flush_cache.php and the reload or graceful restart of apache2. But maybe the --no-warmup and --env=prod has to be set somehow?

The strange behaviour does not stop:
- once again I loaded security.yml from your github-Account
- I changed the ownership and group
- I commented out the last three lines
- I gracefully restarted apache2

Now, I am getting the "500 Internal Server Error" again.
Additionally I turned logging to "debug", here are the entries

in access.log:
xxx.xxx.xxx.xxx - - [14/Sep/2017:10:19:44 +0200] "GET /vmailmanage/domain/ HTTP/1.1" 500 5381 "https://secure.[xxx].net/vmailmanage/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

in error.log:
[Thu Sep 14 10:19:36.718786 2017] [core:debug] [pid 10494] protocol.c(2211): [client xxx.xxx.xxx.xxx:61027] AH03155: select protocol from , choices=h2,http/1.1 for server secure.[xxx].net
[Thu Sep 14 10:19:44.006506 2017] [authz_core:debug] [pid 10494] mod_authz_core.c(809): [client xxx.xxx.xxx.xxx:61027] AH01626: authorization result of Require all granted: granted, referer: https://secure.[xxx].net/vmailmanage/

If I diff the changes since my "initial pull", I get:
\# git status

modified:   ../../.DS_Store
        modified:   ../../.gitignore
        modified:   ../../.idea/deployment.xml
        modified:   ../../.idea/modules.xml
        modified:   ../../.idea/vmailManage.iml
        modified:   ../../.idea/webResources.xml
        modified:   ../../.idea/workspace.xml
        modified:   ../../LICENSE
        modified:   ../../README.md
        modified:   ../.DS_Store
        modified:   ../.htaccess
        modified:   ../AppCache.php
        modified:   ../AppKernel.php
        modified:   ../Resources/.DS_Store
        modified:   ../Resources/views/.DS_Store
        modified:   ../Resources/views/base.html.twig
        modified:   ../Resources/views/base_bottom.html.twig
        modified:   ../Resources/views/default.html.twig
        modified:   ../Resources/views/editAccount.html.twig
        modified:   ../Resources/views/editAlias.html.twig
        modified:   ../Resources/views/editDomain.html.twig
        modified:   ../Resources/views/listAccounts.html.twig
        modified:   ../Resources/views/listAliases.html.twig
        modified:   ../Resources/views/listDomains.html.twig
        modified:   ../Resources/views/security/login.html.twig
        modified:   config.yml
        modified:   config_dev.yml
        modified:   config_prod.yml
        modified:   config_test.yml
        modified:   parameters.yml.dist
        modified:   routing.yml
        modified:   routing_dev.yml
        modified:   security.yml
        modified:   services.yml
        modified:   ../../composer.json
        modified:   ../../composer.lock
        modified:   ../../phpunit.xml.dist
        modified:   ../../src/.DS_Store
        modified:   ../../src/.htaccess
        modified:   ../../src/AppBundle/.DS_Store
        modified:   ../../src/AppBundle/AppBundle.php
        modified:   ../../src/AppBundle/Controller/.DS_Store
        modified:   ../../src/AppBundle/Controller/DefaultController.php
        modified:   ../../src/AppBundle/Controller/EditAliasController.php
        modified:   ../../src/AppBundle/Controller/EditDomainController.php
        modified:   ../../src/AppBundle/Controller/ListAccountsController.php
        modified:   ../../src/AppBundle/Controller/ListAliasesController.php
        modified:   ../../src/AppBundle/Controller/ListDomainsController.php
        modified:   ../../src/AppBundle/Controller/SecurityController.php
        modified:   ../../src/AppBundle/Controller/editAccountController.php
        modified:   ../../src/AppBundle/Entity/Account.php
        modified:   ../../src/AppBundle/Entity/Alias.php
        modified:   ../../src/AppBundle/Entity/Domain.php
        modified:   ../../src/AppBundle/Entity/DomainEditItem.php
        modified:   ../../src/AppBundle/Entity/DomainNewItem.php
        modified:   ../../src/AppBundle/Form/AccountType.php
        modified:   ../../src/AppBundle/Form/AliasType.php
        modified:   ../../src/AppBundle/Form/DomainType.php
        modified:   ../../tests/AppBundle/Controller/DefaultControllerTest.php
        modified:   ../../tests/AppBundle/Controller/EditDomainControllerTest.php
        modified:   ../../tests/AppBundle/Controller/ListDomainsControllerTest.php
        modified:   ../../var/SymfonyRequirements.php
        modified:   ../../var/cache/.gitkeep
        modified:   ../../var/logs/.gitkeep
        modified:   ../../var/sessions/.gitkeep
        modified:   ../../web/.htaccess
        modified:   ../../web/app.php
        modified:   ../../web/app_dev.php
        modified:   ../../web/apple-touch-icon.png
        modified:   ../../web/config.php
        modified:   ../../web/css/main.css
        modified:   ../../web/favicon.ico
        modified:   ../../web/js/main.js
        modified:   ../../web/robots.txt

\# git fetch & git pull tells me "Already up-to-date", so I assume, the changes are only because of changing ownership and permission - this list will give me no hint, right?

Sincerely,

Jochen

**Comment by Andreas-Bresch** [comment]
I think it does not use opcache.
You can try this:
[what-is-the-best-way-to-clean-the-cache-without-running-the-console-command?](https://stackoverflow.com/questions/10815962/what-is-the-best-way-to-clean-the-cache-without-running-the-console-command)
;)

**Comment by Mesqualito** [comment]
You made my day!

"Simply" deleting everything in var/cache takes the changes in security.yml live. Now I can use your Interface without access-control and also with my own user.

Also the cache-Folder now shows only a subfolder "prod", so I can see, it is running in production-mode - even if I don't know, how to switch mode in symfony :-)

Thanks a lot!
Problem solved!

**Comment by Andreas-Bresch** [comment]
:D
