### ISSUE TITLE
Error in during "composer install --no-interaction"

### ISSUE THREAD

**Issue by rflume** [Andreas-Bresch/vmailManage#9]
Hi,
I get an error running the given command on Ubuntu 16.04:

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception
                                                                                            
  [RuntimeException]                                                                        
  An error occurred when executing the "'cache:clear --no-warmup'" command:                 

  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Att  
  empted to load class "DOMDocument" from the global namespace.                             
  Did you forget a "use" statement? in /var/www/html/vmailManage/vendor/symfony/symfony/sr  
  c/Symfony/Component/Config/Util/XmlUtils.php:52                                           
  Stack trace:                                                                              
  #0 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInje  
  ction/Loader/XmlFileLoader.php(368): Symfony\Component\Config\Util\XmlUtils::loadFile('/  
  var/www/html/v...', Array)                                                                
  #1 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInje  
  ction/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFile  
  Loader->parseFileToDOM('/var/www/html/v...')                                              
  #2 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/D  
  ependencyInjection/FrameworkExtension.php(96): Symfony\Component\DependencyInjection\Loa  
  der\XmlFileLoader->load('web.xml')                                                        
  #3 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInje  
  ction/Compiler/Merge in /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Com  
  ponent/Config/Util/XmlUtils.php on line 52                                                
                                                     
Do you have an idea how to solve it?

**Comment by Andreas-Bresch** [comment]
Hey rflume,
what happens if you do this command:
php bin/console cache:clear --no-warmup --env=prod

**Comment by rflume** [comment]
Hi, thank you for your fats reply!
This is the output:

**Workdir: /var/www/html/vmailManage**
php bin/console cache:clear --no-warmup --env=prod

PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(368): Symfony\Component\Config\Util\XmlUtils::loadFile('/var/www/html/v...', Array)
#1 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/var/www/html/v...')
#2 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(96): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(59): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, O in /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52

**Comment by Andreas-Bresch** [comment]
Maybe you forgot to install php7.0-xml?

first step:
apt-get install php7.0 php7.0-mysql php7.0-xml php7.0-opcache php-apcu

**Comment by rflume** [comment]
That was it. Shame on me...
Thank you for your help and sorry for bothering you with that!
